name: common_utils
description: Flutter common utils library.DateUtil, NumUtil, ScreenUtil, RegexUtil, ObjectUtil, WidgetUtil.
version: 1.0.4
author: thl <863764940@qq.com>
homepage: https://github.com/Sky24n/common_utils

environment:
    sdk: ">=1.19.0 <3.0.0"
